INSERT INTO users (first_name, last_name, username, email, hashed_password) VALUES
('Demo','User', 'DemoUser','demoUser@demoEmail.io','p@sswordDemo1'),
('Kendra','Chauntell','KChauntell','kchauntell@awesome.io','Kendr@89');


INSERT INTO flashcards (course, question, answer, reference, user_id) VALUES
( 'Java',
  'When you change a value of one type to another type it is known as?',
  'Type Casting',
  'https://www.udemy.com/course/pyramid-academy/learn/quiz/4783562#overview',
  1 ),
( 'Java',
  'An array is...',
  'A collection of values of the same datatype',
  'https://www.udemy.com/course/pyramid-academy/learn/quiz/4783316#overview',
  1 ),
( 'Java',
  'The Java HashMap class implements what interface?',
  'The Map Interface',
  'https://www.udemy.com/course/pyramid-academy/learn/quiz/4783644#overview',
  1 ),
( 'Java',
  'Method overriding is also known as?',
  'Runtime Polymorphism',
  'https://www.udemy.com/course/pyramid-academy/learn/quiz/4783546#overview',
  1 ),
( 'Java',
  'What is inheritance in Java?',
  'Inheritance is the process that enables one class to acquire the properties (methods and variables) of another class.',
  'https://www.udemy.com/course/pyramid-academy/learn/quiz/4783530#overview',
  1 ),
( 'Spring/SpringBoot',
  'What is Spring?',
  "The Spring framework is an application framework and inversion of control container for the Java platform. The framework's core features can be used by any Java application, but there are extensions for building web applications on top of the Java JEE platform",
  "https://www.udemy.com/course/pyramid-academy/learn/quiz/4793244#overview",
  2 ),
( "Spring/SpringBoot",
  "What is Inversion of Control?",
  "Inversion of Control is the approach to outsourcing the creation and management of objects to a factory or spring container",
  "https://www.udemy.com/course/pyramid-academy/learn/quiz/4793244#overview",
  2 ),
( "React",
  "What are expressions in JSX?",
  "An expression can be a React variable, property, or any other valid JS expression. JSX will execute the expression and return the result",
  "What are expressions in JSX?",
  2 ),
("React",
  "How can you refer to the state object that might reside anywhere in the component?",
  "this.state.propertyName",
  "https://www.udemy.com/course/pyramid-academy/learn/quiz/4793992#overview",
  2 ),
("React",
  "What are the three phases of the component life cycle?",
  "Mounting, Updating, Unmounting",
  "https://www.udemy.com/course/pyramid-academy/learn/quiz/4793994#overview",
  2 );
